schema_version = "1.0.0"

id = "step_forge"
version = "3.9.8"
name = "StepForge"
tagline = "Import & export STEP/STP, pure Python"
maintainer = "Philip Gruenenfelder"
type = "add-on"

website = "https://github.com/RandomLambda/StepForge"
support = "https://github.com/RandomLambda/StepForge/issues"

tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Import .step/.stp files from disk and export STEP files to disk"
